// Generated by CoffeeScript 1.9.0
var password, unipassman, username, _ref;

unipassman = require('./unipassman');

_ref = process.argv.slice(2), username = _ref[0], password = _ref[1];

if (!((username != null) || (username === '--help' || username === '-h'))) {
  console.error("Username is required. Usage:\n\nRead:\n  unipassman username\n\nWrite:\n  unipassman username password\n\nCheck password manager availability:\n  unipassman --check\n");
  process.exit(username != null ? 0 : 1);
}

if (username === '--check') {
  return unipassman.getManager(function(err, name) {
    if (err) {
      console.error(err.message);
      process.exit(1);
    }
    return console.log(name);
  });
}

if (password != null) {
  return unipassman.write(username, password, function(err) {
    if (err) {
      console.error(err);
      return process.exit(1);
    }
  });
  unipassman.read(username, function(err, password) {
    if (err) {
      console.error(err);
      process.exit(1);
    }
    return console.log(password);
  });
}
